# Generated by Django 5.0.6 on 2024-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Procut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description_short", models.TextField(max_length=255)),
                ("description_long", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_imgs/%Y/%m"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("marketing_price", models.FloatField()),
                ("marketing_price_promotional", models.FloatField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("V", "Variation"), ("S", "Simple")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
