# Generated by Django 5.0.6 on 2024-05-18 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Procut",
            new_name="Product",
        ),
    ]
