# Generated by Django 5.0.6 on 2024-05-18 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_variation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variation",
            options={"verbose_name": "Variation", "verbose_name_plural": "Variations"},
        ),
    ]
