# Generated by Django 5.0.6 on 2024-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="marketing_price",
            field=models.FloatField(verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="product",
            name="marketing_price_promotional",
            field=models.FloatField(default=0, verbose_name="Promotion Price"),
        ),
    ]
