# Generated by Django 5.0.6 on 2024-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
